name = "loophole"
main = "worker/index.ts"
compatibility_date = "2026-09-27"

[[d1_databases]]
binding = "DB"
database_name = "loophole-db"
database_id = "a2f0aed4-567e-41ec-9c72-1c8a4a6decc3"
migrations_dir = "migrations"

[triggers]
crons = ["*/15 * * * *"]

[vars]
ENVIRONMENT = "production"
# Store ADMIN_TOKEN with: wrangler secret put ADMIN_TOKEN

[assets]
directory = "./frontend/dist"
binding = "ASSETS"

