import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import'./styles/app.css';

type Source={id:string,name:string};type Video={id:string;sourceId:string;sourceName:string;externalId:string;title:string;thumbnailUrl?:string;originalUrl:string;creator?:string;duration?:number;publishedAt?:string;viewCount?:number;downloadAllowed?:boolean;downloadUrl?:string};
const api=async<T>(url:string)=>{const r=await fetch(url);if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json() as Promise<T>};
function fmtDuration(s?:number){if(s==null)return'';const h=Math.floor(s/3600),m=Math.floor(s%3600/60),x=s%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(x).padStart(2,'0')}`:`${m}:${String(x).padStart(2,'0')}`}
function App(){const[sources,setSources]=useState<Source[]>([]),[videos,setVideos]=useState<Video[]>([]),[source,setSource]=useState(''),[q,setQ]=useState(''),[theme,setTheme]=useState(localStorage.getItem('theme')||'system'),[loading,setLoading]=useState(true),[err,setErr]=useState('');
useEffect(()=>{api<{sources:Source[]}>('/api/sources').then(x=>setSources(x.sources)).catch(e=>setErr(e.message))},[]);
useEffect(()=>{setLoading(true);const p=new URLSearchParams({limit:'40'});if(source)p.set('source',source);if(q)p.set('q',q);api<{videos:Video[]}>('/api/videos?'+p).then(x=>setVideos(x.videos)).catch(e=>setErr(e.message)).finally(()=>setLoading(false))},[source,q]);
useEffect(()=>{document.documentElement.dataset.theme=theme},[theme]);
return <div className="app"><header><a className="logo" href="/">LOOPHOLE</a><nav><a href="/">Home</a><a href="#all">All</a><a href="#sources">Sources</a></nav><form onSubmit={e=>{e.preventDefault();setQ((e.currentTarget.elements.namedItem('q') as HTMLInputElement).value)}}><input name="q" placeholder="Search videos…" defaultValue={q}/><button>Search</button></form><select aria-label="Theme" value={theme} onChange={e=>{setTheme(e.target.value);localStorage.setItem('theme',e.target.value)}}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></header><main><section className="hero"><div><p className="eyebrow">MULTI-SOURCE VIDEO AGGREGATOR</p><h1>Everything in one feed.</h1><p className="sub">Permitted metadata from enabled sources, linked back to the original websites.</p></div></section><div id="sources" className="filters"><button className={!source?'active':''} onClick={()=>setSource('')}>All</button>{sources.map(s=><button key={s.id} className={source===s.id?'active':''} onClick={()=>setSource(s.id)}>{s.name}</button>)}</div>{err&&<div className="notice">Unable to load some data. {err}</div>}{loading?<div className="grid">{Array.from({length:12},(_,i)=><div className="skeleton" key={i}/>)}</div>:<div id="all" className="grid">{videos.map(v=><article className="card" key={v.id}><a href={v.originalUrl} target="_blank" rel="noopener noreferrer"><div className="thumb"><img loading="lazy" src={v.thumbnailUrl||'/placeholder.svg'} alt=""/><span>{fmtDuration(v.duration)}</span></div><div className="body"><h2>{v.title}</h2><p className="meta"><b>{v.sourceName}</b>{v.creator&&<> · {v.creator}</>}{v.viewCount!=null&&<> · {Intl.NumberFormat('en',{notation:'compact'}).format(v.viewCount)} views</>}</p><p className="date">{v.publishedAt?new Date(v.publishedAt).toLocaleString():''}</p><div className="actions"><span>Open original</span>{v.downloadAllowed&&v.downloadUrl&&<a className="download" href={v.downloadUrl}>Download</a>}</div></div></a></article>)}</div>}{!loading&&!videos.length&&<div className="empty">No videos found.</div>}</main><footer>Loophole · Aggregator only · Source sites remain responsible for their media.</footer></div>}
createRoot(document.getElementById('root')!).render(<App/>);
